#!/bin/bash

for directory in */
do
    dir_array=($directory)
    if [ ${dir_array[0]}=="The" ] || [ ${dir_array[0]}=="Die" ]
    then
        article=${dir_array[0]}
        i=1
        while true
        do
            if [ $dir_array[$i] != "-" ]
            then
                dir_array[($i-1)]="${dir_array[$i]}"
                i=($i+1)
            else
                dir_array[($i-1)]="${dir_array[($i-1)]}"","
                dir_array[$i]="$article"
                break
            fi
        done
        new_dir="${dir_array[*]}"
        mv -- "$directory" "$new_dir"
    fi
done
