#!/bin/bash

for directory in */
do
    dir_array=($directory)
    if [ "${dir_array[0]}" == "The" ] || [ "${dir_array[0]}" == "Die" ]
    then
        echo ${dir_array[0]}
#        article=${dir_array[1]}
#        i=2
#        while true
#        do
#            if (( dir_array[i] == "-" ))
#            then
#                dir_array[($i-1)]="${dir_array[($i-1)]}""\,"
#                dir_array[$i]="$article"
#                break
#            else
#                dir_array[($i-1)]="${dir_array[$i]}"
#                i=($i+1)
#            fi
#        done
#        new_dir="${dir_array[*]}"
#        mv -- "$directory" "$new_dir"
    fi
done
